// speechsynthesisstream.dart

// THIS FILE IS GENERATED AUTOMATICALLY AND SHOULD NOT BE EDITED DIRECTLY.

// ignore_for_file: unused_import
// ignore_for_file: constant_identifier_names, non_constant_identifier_names
// ignore_for_file: no_leading_underscores_for_local_identifiers

import 'dart:ffi';

import 'package:ffi/ffi.dart';

import '../../../com/iinspectable.dart';
import '../../../combase.dart';
import '../../../exceptions.dart';
import '../../../macros.dart';
import '../../../types.dart';
import '../../../utils.dart';
import '../../../win32/api_ms_win_core_winrt_string_l1_1_0.g.dart';
import '../../../winrt_callbacks.dart';
import '../../../winrt_helpers.dart';
import '../../foundation/collections/ivectorview.dart';
import '../../foundation/iasyncoperation.dart';
import '../../foundation/iclosable.dart';
import '../../internal/hstring_array.dart';
import '../../storage/streams/enums.g.dart';
import '../../storage/streams/ibuffer.dart';
import '../../storage/streams/icontenttypeprovider.dart';
import '../../storage/streams/iinputstream.dart';
import '../../storage/streams/ioutputstream.dart';
import '../../storage/streams/irandomaccessstream.dart';
import '../../storage/streams/irandomaccessstreamwithcontenttype.dart';
import '../core/itimedmetadatatrackprovider.dart';
import '../core/timedmetadatatrack.dart';
import '../imediamarker.dart';
import 'ispeechsynthesisstream.dart';

/// Supports reading and writing audio data generated by the speech
/// synthesis engine (voice) to/from a random access stream.
///
/// {@category Class}
/// {@category winrt}
class SpeechSynthesisStream extends IInspectable
    implements
        ISpeechSynthesisStream,
        IRandomAccessStreamWithContentType,
        IContentTypeProvider,
        IRandomAccessStream,
        IOutputStream,
        IClosable,
        IInputStream,
        ITimedMetadataTrackProvider {
  SpeechSynthesisStream.fromRawPointer(super.ptr);

  // ISpeechSynthesisStream methods
  late final _iSpeechSynthesisStream = ISpeechSynthesisStream.from(this);

  @override
  List<IMediaMarker> get markers => _iSpeechSynthesisStream.markers;

  // IContentTypeProvider methods
  late final _iContentTypeProvider = IContentTypeProvider.from(this);

  @override
  String get contentType => _iContentTypeProvider.contentType;

  // IRandomAccessStream methods
  late final _iRandomAccessStream = IRandomAccessStream.from(this);

  @override
  int get size => _iRandomAccessStream.size;

  @override
  set size(int value) => _iRandomAccessStream.size = value;

  @override
  IInputStream? getInputStreamAt(int position) =>
      _iRandomAccessStream.getInputStreamAt(position);

  @override
  IOutputStream? getOutputStreamAt(int position) =>
      _iRandomAccessStream.getOutputStreamAt(position);

  @override
  int get position => _iRandomAccessStream.position;

  @override
  void seek(int position) => _iRandomAccessStream.seek(position);

  @override
  IRandomAccessStream? cloneStream() => _iRandomAccessStream.cloneStream();

  @override
  bool get canRead => _iRandomAccessStream.canRead;

  @override
  bool get canWrite => _iRandomAccessStream.canWrite;

  // IOutputStream methods
  late final _iOutputStream = IOutputStream.from(this);

  @override
  Pointer<COMObject> writeAsync(IBuffer? buffer) =>
      _iOutputStream.writeAsync(buffer);

  @override
  Future<bool> flushAsync() => _iOutputStream.flushAsync();

  // IClosable methods
  late final _iClosable = IClosable.from(this);

  @override
  void close() => _iClosable.close();

  // IInputStream methods
  late final _iInputStream = IInputStream.from(this);

  @override
  Pointer<COMObject> readAsync(
          IBuffer? buffer, int count, InputStreamOptions options) =>
      _iInputStream.readAsync(buffer, count, options);

  // ITimedMetadataTrackProvider methods
  late final _iTimedMetadataTrackProvider =
      ITimedMetadataTrackProvider.from(this);

  @override
  List<TimedMetadataTrack> get timedMetadataTracks =>
      _iTimedMetadataTrackProvider.timedMetadataTracks;
}
